server:
  port: 8095
  servlet:
    context-path: /store/location

logging:
  file: logs/location-store.log
  level:
    #org.springframework.web: DEBUG
#    guru.springframework.controllers: DEBUG
    org:
      springframework:
        data:
          cassandra:
            core:
              cql:
                CqlTemplate: DEBUG
    org.hibernate: DEBUG

#  pattern:
#    console: '%d %-5level %logger : %msg%n'
#    file: '%d %-5level [%thread] %logger : %msg%n'